### ISSUE TITLE
[Web] Tree Shaking

### ISSUE THREAD

**Issue by nandorojo** [callstack/react-native-builder-bob#154] opened 2021-04-07 00:27 UTC
## Ask your Question

Hey there, thanks for this awesome package, it's seriously a life saver.

I'm experiencing an issue with my package, Dripsy, on web. It appears that importing `dripsy` is importing all of React Native Web, adding about 500kb more than I need to my site. I have `sideEffects: false` in my `package.json` file, but this seems to have no effect.

I was wondering if you have any suggestions for how to solve that. Should I try using the `react-native-web` babel plugin in my babel config for bob? I'm not that familiar with Babel and how it works, so I figured I'd ask. I'm using Expo web, and have `dripsy` in my transpile modules file, so I figured this would apply the RNW babel plugin to it. But it seems like it isn't.

Let me know if any suggestions come to mind. Thanks again!

**Comment by nandorojo** [comment] 2021-04-07 02:12
I switched my build scripts to expo-module-scripts, and that helped a lot. Seems like that's my answer.

**Comment by nandorojo** [comment] 2021-04-07 21:28
I'll reopen to propose changing to `expo-module-scripts` as the default build script. I've tried this for 2 different react native packages now, including Dripsy and react-native-safe-area-context. In both cases, I was able to reduce web bundle size by ~400kb, which is significant. In both cases, it took like 15 minutes to switch to `expo-module prepare`.

I'd be happy to submit a PR to Bob for this, just let me know.

**Comment by satya164** [comment] 2021-04-08 02:59
I don't see why whole react-native-web would be imported with bob's output and not with expo-module-scripts's output. What does it do internally?

You should be using react-native-web babel plugin in your app when building for web anyway but perhaps expo-build-scripts already includes it. Including it in the library's build scripts isn't safe since we're not building packages specifically for react-native-web.

**Comment by nandorojo** [comment] 2021-04-08 03:05
Honestly, I'm not sure how it works. @evanbacon will know better, seems like it's some sort of webpack tree shaking optimization that `expo-module` does.

I refactored a few of my packages using `expo-module prepare` instead of `bob build`, though, and suddenly my Next.js app wasn't importing all of RNW, and my bundle size dropped. I wish I could offer more insight into why that is.

**Comment by nandorojo** [comment] 2021-04-08 15:49
Another instance of this is `@react-navigation/core`.

I use `<NavigationContainer>` in my `pages/_app.tsx` for Next.js.

This is without `NavigationContainer`:

<img width="237" alt="Screen Shot 2021-04-08 at 11 44 43 AM" src="https://user-images.githubusercontent.com/13172299

And this is with `NavigationContainer`:

<img width="215" alt="Screen Shot 2021-04-08 at 11 45 36 AM" src="https://user-images.githubusercontent.com/13172299/114057233-62fd9380-9860-11eb-9e81-3bc4b24e1801.png">
/114057208-5da04900-9860-11eb-9582-17adf597ecf0.png">

I could try forking `@react-navigation/core` to see if using `expo-module prepare` instead solves this. 

## Context

[Here's](https://github.com/th3rdwave/react-native-safe-area-context/pull/189) a PR I did for react-native-safe-area-context as an example.

[This](https://github.com/nandorojo/dripsy/issues/41) is a related issue for Dripsy, where I solved it.

**Comment by satya164** [comment] 2021-04-08 16:38
But what does it do? bob compiles the files down to relatively modern ES5 so that's gonna increase bundle size due to generated code and polyfills, the code is also not minified so it'll be bigger (you'd minify in prod anyway). You can customize what gets compiled with a browserlist config or your custom babel config. does expo module scripts compile down? if not it'll be smaller but it won't work on slightly older browsers.

You're saying that with Bob your whole react native web gets included but I don't see why that would be since bob doesn't bundle any code, it just compiles individual files.

What does expo module scripts do?

**Comment by nandorojo** [comment] 2021-09-03 13:22
I'm still trying to get to the bottom do why this is happening. Could it be as simple as, compiling with TSC is better for preserving tree shaking for web?

It's my understanding that on iOS and Android, apps resolve to the `package.json` → `react-native` field, which typically point to the source directly. For web, the behavior is different.

This really isn't my area of expertise, but I've run multiple experiments on different libraries now. In each case, expo-module-scripts results in essentially no bundle size increase, while Bob's web output causes hundreds of KB increases.

https://github.com/th3rdwave/react-native-safe-area-context/pull/189

**Comment by EvanBacon** [comment] 2021-12-15 00:55
On web, we preserve import/export syntax so we can transform `react-native` -> `react-native-web`. Generally I find that tools will transform `import { View } from 'react-native'` to `const ReactNative = require('react-native'); ReactNative.View...` meaning we can't use babel to ignore paths later.

**Comment by intergalacticspacehighway** [comment] 2021-12-15 11:18
^I can confirm that bob exports es module and commonjs bundles in two separate directories. As long as the bundler picks es modules bundle path, transformers can get the `import { View } from "react-native"` (es modules) code.

**Comment by nandorojo** [comment] 2022-06-14 04:23
To add some context here for reference, it seems like picking up CommonJS / transpiled code would be the issue:

![image](https://user-images.githubusercontent.com/13172299/173492803-671a928b-7d9b-412f-a392-30ceaf4b8d62.jpeg)

I think using `experimental.esmExternals` (I forget the exact field name) from Next.js should solve this - I'll do some tests to confirm it's working.

**Comment by merrywhether** [comment] 2023-02-25 02:38
@nandorojo This should be addressed by #363 and then https://github.com/software-mansion/react-native-svg/pull/1993. Together those will fix the module output of `react-native-svg` and enable proper tree-shaking. I've attached the bundle analyzer output from my project.

Current:
<img width="790" alt="Screenshot 2023-02-24 at 6 06 26 PM" src="https://user-images.githubusercontent.com/4097742/221331980-907ba7c8-e504-482c-a58e-04f6f59ef616.png">

After changes:
<img width="924" alt="Screenshot 2023-02-24 at 6 23 36 PM" src="https://user-images.githubusercontent.com/4097742/221331983-c329f7a0-a1cd-4d53-889e-d57e3add058d.png">

**Closed** 2023-02-26 18:42 UTC
Labels: question
