### ISSUE TITLE
Cannot run 'yarn example ios'

### ISSUE THREAD

**Issue by daniel-keen** [callstack/react-native-builder-bob#224] opened 2022-02-02 10:14 UTC
## Environment

OS: Mac OS 12.1 Monterey
yarn version: v1.22.17

## Description

I have been following "[react native: native modules](https://reactnative.dev/docs/native-modules-setup)" tutorial. 
Unfortunately at the "yarn example ios" step I receive a bunch of log messages followed by this error: 
`error Command failed with exit code 1.`

Logs attached to the issue:
[yarn_example_ios_logs.txt](https://github.com/callstack/react-native-builder-bob/files/7985469/yarn_example_ios_logs.txt)

## Reproducible Demo

Simply follow the tutorial steps.

**Comment by nikhil-kumar-160** [comment] 2022-02-02 13:34
The issue is related to flipper. I would suggest commenting out the flipper plugin code in Podfile inside ./example/ios/
Run pod install once again and try to run the app after that
It will fix the crash

Reason is, the library still uses RN 0.64.3 and the flipper issue has been fixed in new RN versions

**Comment by thexdd** [comment] 2022-02-09 21:22
@nikhil-kumar-160 Thank you for the answer! Indeed after commenting the `use_flipper!({ 'Flipper' => '0.80.0' })` line, yarn example iOS successfully worked!

**Comment by ugglr** [comment] 2022-03-22 03:45
Same problem, above solved the issue.

**Comment by satya164** [comment] 2023-07-04 10:59
Can you provide repro steps for the issue?

**Closed** 2023-10-11 18:05 UTC
Labels: needs-repro
