### ISSUE TITLE
Unresolved reference: facebook

### ISSUE THREAD

**Issue by dhananjayspeed** [callstack/react-native-builder-bob#353] opened 2023-01-23 06:21 UTC
### Description

Unable to create native module and android studio showing error "Unresolved reference: facebook"

### Packages

- [X] create-react-native-library
- [ ] react-native-builder-bob

### Selected options

Execution failed for task ':generateDebugRFile'.
> Could not resolve all files for configuration ':debugCompileClasspath'.
   > Could not find com.facebook.react:react-native:.
     Required by:
         project :

### Environment

System:
    OS: macOS 13.0.1
    CPU: (8) x64 Apple M1
    Memory: 27.35 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.17.6 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.1.1 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.1 => 0.71.1 
    react-native-macos: Not Found

**Comment by babeone** [comment] 2023-02-07 14:33
I have the same issue, any solution?  Thanks :)

**Comment by ysfzrn** [comment] 2023-02-07 17:42
Maybe you can use this "com.facebook.react:react-android" instead of "com.facebook.react:react-native"

**Comment by Sunbreak** [comment] 2023-02-24 10:24
Probably duplicate of #361, fixed by #362 

Try add `+` back

```diff
   // For < 0.71, this will be from the local maven repo
   // For > 0.71, this will be replaced by `com.facebook.react:react-android:$version` by react gradle plugin
   //noinspection GradleDynamicVersion
-  implementation "com.facebook.react:react-native"
+  implementation "com.facebook.react:react-native:+"
```

**Comment by chandreshgroww** [comment] 2023-02-25 12:04
@Sunbreak tried your approach of adding `+` but it is not working, still getting unresolved reference: facebook

I have built a clean project from create-react-native-library@latest, any suggestions?

**Comment by Sunbreak** [comment] 2023-02-25 13:37
> @Sunbreak tried your approach of adding `+` but it is not working, still getting unresolved reference: facebook
> 
> I have built a clean project from create-react-native-library@latest, any suggestions?

Could you share you clean project?

**Comment by chandreshgroww** [comment] 2023-02-26 11:13
@Sunbreak I haven't done any modification in the project created from `npx create-react-native-library@latest my-lib`

and performed yarn

then opened the android folder present in root (not in example folder)

and it shows unresolved reference: facebook

**Comment by Sunbreak** [comment] 2023-02-26 12:45
> @Sunbreak I haven't done any modification in the project created from `npx create-react-native-library@latest my-lib`
> 
> and performed yarn
> 
> then opened the android folder present in root (not in example folder)
> 
> and it shows unresolved reference: facebook

Could you shared you code?

Different environment would use different version of `create-react-native-library` and generate different yarn.lock, especially react-native version

I've got 3 macOS, 1 Linux and 1 Windows PC. None of them use the same version of Nodejs/create-react-native-library/react-antive version when calling `npx create-react-native-library@latest my-lib`

**Comment by RalissonMattias** [comment] 2023-02-27 01:28
I was getting the same issue so I used this  `com.facebook.react:react-android:+` instead of `com.facebook.react:react-native:+`. Detail, my React Native version is `0.71.3`

**Comment by Sunbreak** [comment] 2023-02-27 02:51
> I was getting the same issue so I used this `com.facebook.react:react-android:+` instead of `com.facebook.react:react-native:+`. Detail, my React Native version is `0.71.3`

Yep. That's the point.

> ### Summary
> Fix #361 which is introduced by [4eff3eb](https://github.com/callstack/react-native-builder-bob/commit/4eff3ebfcbbb1bc4961c5567ea4d1e75d3c5a72d)
> 
> According to [outage postmortem](https://reactnative.dev/blog/2023/01/27/71rc1-android-outage-postmortem), we could revert the noinspection version `+` back for react-native@0.70.*
> 
> ### Test plan

The outage postmortem shows why `0.71.3` use `react-android` instead of `react-native`

**Comment by reyn-nova** [comment] 2023-03-31 07:23
@dhananjayspeed @babeone @chandreshgroww 

in android/buid.gradle I changed the dependencies to this version and press Gradle Sync again, in what I have tried solve facebook import

`classpath 'com.android.tools.build:gradle:3.5.3'`

**Comment by reyn-nova** [comment] 2023-03-31 07:24
no more facebook import reference error

![Screen Shot 2023-03-31 at 14 23 43](https://user-images.githubusercontent.com/39117076/229052057-1a9c1d0c-9229-4b58-9ace-3085b5e3eb79.png)

**Comment by pasquale95** [comment] 2023-05-05 08:22
The suggestion from @Sunbreak solved the issue for me. In addition, I add to add the following line to `gradle.properties`:
```
org.gradle.jvmargs=-Xmx4096M -XX:MaxMetaspaceSize=512m
```

**Closed** 2023-07-04 11:02 UTC
Labels: bug

**Comment by ko-devHong** [comment] 2024-04-17 08:21
> I was getting the same issue so I used this `com.facebook.react:react-android:+` instead of `com.facebook.react:react-native:+`. Detail, my React Native version is `0.71.3`

current default install version `"react-native": "0.73.6",`

**Comment by pavel-bolhovitin** [comment] 2024-10-22 07:40
1. In the `package.json` add:
```
"peerDependencies": {
  "react-native": "*"
}
```
2. npm i
3. In the `android\build.gradle` add:
```
allprojects {
  repositories {
    maven {
      // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
      url("$rootDir/../node_modules/react-native/android")
    }
    maven {
      // Android JSC is installed from npm
      url("$rootDir/../node_modules/jsc-android/dist")
    }
    mavenCentral {
      // We don't want to fetch react-native from Maven Central as there are
      // older versions over there.

      content {
        excludeGroup "com.facebook.react"
      }
    }
    google()
    maven { url 'https://www.jitpack.io' }
  }
}
```
4. In the `android\gradle.properties` add:
```
# AndroidX package structure to make it clearer which packages are bundled with the
# Android operating system, and which are packaged with your app's APK
# https://developer.android.com/topic/libraries/support-library/androidx-rn
android.useAndroidX=true
# Automatically convert third-party libraries to use AndroidX
android.enableJetifier=true
```
5. In the android studio > File > Sync project with gradle files

**Comment by ALTHGA** [comment] 2024-12-26 21:17
I am same problem:

```
Failed to resolve: com.facebook.react:react-native:+
Show in Project Structure dialog
Affected Modules: android
```

My Build Gradle:

```
buildscript {
  // Buildscript is evaluated before everything else so we can't use getExtOrDefault
  def kotlin_version = rootProject.ext.has("kotlinVersion") ? rootProject.ext.get("kotlinVersion") : project.properties["BlePrinter_kotlinVersion"]

  repositories {
    google()
    mavenCentral()
  }

  dependencies {
    classpath "com.android.tools.build:gradle:7.4.2"
    // noinspection DifferentKotlinGradleVersion
    classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
  }
}

def reactNativeArchitectures() {
  def value = rootProject.getProperties().get("reactNativeArchitectures")
  return value ? value.split(",") : ["armeabi-v7a", "x86", "x86_64", "arm64-v8a"]
}

def isNewArchitectureEnabled() {
  return rootProject.hasProperty("newArchEnabled") && rootProject.getProperty("newArchEnabled") == "true"
}

apply plugin: "com.android.library"
apply plugin: "kotlin-android"

if (isNewArchitectureEnabled()) {
  apply plugin: "com.facebook.react"
}

def getExtOrDefault(name) {
  return rootProject.ext.has(name) ? rootProject.ext.get(name) : project.properties["BlePrinter_" + name]
}

def getExtOrIntegerDefault(name) {
  return rootProject.ext.has(name) ? rootProject.ext.get(name) : (project.properties["BlePrinter_" + name]).toInteger()
}

def supportsNamespace() {
  def parsed = com.android.Version.ANDROID_GRADLE_PLUGIN_VERSION.tokenize('.')
  def major = parsed[0].toInteger()
  def minor = parsed[1].toInteger()

  // Namespace support was added in 7.3.0
  return (major == 7 && minor >= 3) || major >= 8
}

android {
  if (supportsNamespace()) {
    namespace "com.bleprinter"

    sourceSets {
      main {
        manifest.srcFile "src/main/AndroidManifestNew.xml"
      }
    }
  }

  compileSdkVersion getExtOrIntegerDefault("compileSdkVersion")

  defaultConfig {
    minSdkVersion getExtOrIntegerDefault("minSdkVersion")
    targetSdkVersion getExtOrIntegerDefault("targetSdkVersion")

  }

  buildTypes {
    release {
      minifyEnabled false
    }
  }

  lintOptions {
    disable "GradleCompatible"
  }

  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }
}

repositories {
  mavenCentral()
  google()
}

def kotlin_version = getExtOrDefault("kotlinVersion")

dependencies {
  // For < 0.71, this will be from the local maven repo
  // For > 0.71, this will be replaced by `com.facebook.react:react-android:$version` by react gradle plugin
  //noinspection GradleDynamicVersion
  implementation "com.facebook.react:react-native:+"
  implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
}

```
