### ISSUE TITLE
RNAwesomeLibrarySpec.h' file not found

### ISSUE THREAD

**Issue by Ahmedhamed77** [callstack/react-native-builder-bob#640] opened 2024-09-26 13:10 UTC
### Description

steps to reproduce 
```
1- npx create-react-native-library@latest awesome-library
2- choose Turbo module (requires new arch)
3- push the repo to github 
4- install the package in a react-native app 
```
so the `package.json` will look like this
```
    "react": "18.3.1",
    "react-native": "0.75.3",
    "react-native-awesome-library": "https://github.com/Ahmedhamed77/react-native-awesome-library.git"
```

then in the project folder 
```
cd ios && bundle install && RCT_NEW_ARCH_ENABLED=1 bundle exec pod install

```

then `yarn ios`

I get this error
```
TestApp/node_modules/react-native-awesome-library/ios/AwesomeLibrary.h:3:9: 'RNAwesomeLibrarySpec.h' file not found

#import "RNAwesomeLibrarySpec.h"
```

in the example app inside the package itself the generated files are exist but if I install the lib from GitHub the generated files are not generated with `pod install` 

do I miss something here ? 

### Packages

- [X] create-react-native-library
- [ ] react-native-builder-bob

### Selected options

already described it

### Link to repro

https://github.com/Ahmedhamed77/react-native-awesome-library

### Environment

info Fetching system and libraries information...
(node:8534) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
System:
  OS: macOS 14.3.1
  CPU: (8) arm64 Apple M1
  Memory: 81.25 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 21.6.2
    path: /opt/homebrew/bin/node
  Yarn:
    version: 3.6.4
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.2.4
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2024.01.22.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2411.12071903
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.11
    path: /usr/bin/javac
  Ruby:
    version: 3.3.0
    path: /opt/homebrew/opt/ruby/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.75.3
    wanted: 0.75.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: true

**Comment by LuongTruong** [comment] 2024-10-01 10:19
Hey @Ahmedhamed77 , I have the same issue. 

Tried to look around and saw that the file `RNAwesomeLibrarySpec.h` should be found inside the build -> generated folder from ios. Following, this folder wouldn't be committed to Git.

I am also looking away to re-generate this file using Codegen after integrating the library to the project.

**Comment by satya164** [comment] 2024-10-01 10:33
Duplicate of https://github.com/callstack/react-native-builder-bob/discussions/644

**Closed by satya164** 2024-10-01 10:33 UTC
Labels: bug

**Comment by LuongTruong** [comment] 2024-10-02 03:35
Hello @satya164 , thanks for the duplicated issue. I read it. However, it makes me confuse.

According to [Issue 644](https://github.com/callstack/react-native-builder-bob/discussions/644), the issue is
- The author creates a library, adds the library to the app. HE IS ABLE TO BUILD THE APP but need to change the import link from `import { multiply } from 'testlib'` to `import { multiply } from 'testlib/src'` to make the app work.

Our issue:
- WE ARE NOT ABLE TO BUILD THE APP due to the missing of `RNAwesomeLibrarySpec.h` file.

Following, I also add the field `prepack` to `package.json` of lib.
When pulling the lib to the actual app. I receive the error: ` Packing the package failed (exit code 1...`

<img width="1704" alt="Screenshot 2024-10-02 at 10 30 12" src="https://github.com/user-attachments/assets/13ce6268-2987-4a40-bff3-7a4ca51cf5a9">

Please let me know if we need to do anything else so we can build the iOS without missing `RNAwesomeLibrarySpec.h` file.

If you found this is not duplicated with the issue 644, please reopen the issue. Many thanks!

**Comment by LuongTruong** [comment] 2024-10-04 08:06
Hello @Ahmedhamed77 , I found a solution for this one and will leave it here in case if you come back or anyone needs it later.

I am able to create a library and integrate it to another react native app.

### Create a library using version 0.41.2

`npx create-react-native-library@0.41.2 awesome-library`

### When pull the lib to your app, make sure you have necessary files and folders

In my case, they are:

1. `android`
2. `ios`
3. `lib`
4. `src`
5. `LICENSE`
6. `package.json`
7. `*.podspec`
8. `README.md`

### Final

- For iOS, I run `bundle install && RCT_NEW_ARCH_ENABLED=1 bundle exec pod install`, then open the Xcode project and build as normal.
- For Android, I change `newArchEnabled=true` to make sure the `NativeAwesomeLibrarySpec` is built, then open Android Studio and build as normal.
